<!DOCTYPE html>
<html>
<head>

<meta charset="utf-8">

<title>System Report</title>

<style>

body{
    font-family: Arial, sans-serif;
    color:#222;
    margin:30px;
}

.header{
    text-align:center;
    border-bottom:2px solid #333;
    padding-bottom:15px;
    margin-bottom:25px;
}

.header h1{
    margin:0;
    font-size:28px;
}

.header h2{
    margin-top:8px;
    color:#666;
    font-weight:normal;
}

.info{
    margin-bottom:25px;
}

.info p{
    margin:5px 0;
}

.section{
    margin-top:25px;
}

.section-title{
    background:#f3f4f6;
    padding:10px;
    font-size:18px;
    font-weight:bold;
    border-left:5px solid #2563eb;
}

table{
    width:100%;
    border-collapse:collapse;
    margin-top:10px;
}

table th,
table td{
    border:1px solid #ddd;
    padding:10px;
}

table th{
    background:#f9fafb;
}

.footer{
    margin-top:50px;
    text-align:center;
    font-size:12px;
    color:#777;
}

@media print{

    .no-print{
        display:none;
    }

    body{
        margin:0;
        padding:20px;
    }

}

</style>

</head>
<body>

<div class="header">

  <div class="">
    <img src="{{ asset('images/clinic-logo/logo.png') }}" alt="Clinic Logo" style="border-radius:50%; width:100px;height:100px; object-fit:contain; margin-bottom:10px; ">
  </div>
    <h1 style="margin-bottom:5px;">
        Quraishi Dental Clinic
    </h1>

    <h2 style="margin:0;">
         System Report
    </h2>

</div>

<div class="info">

    <p>
        <strong>From:</strong>
        {{ $fromDate }}
    </p>

    <p>
        <strong>To:</strong>
        {{ $toDate }}
    </p>

    <p>
        <strong>Generated At:</strong>
        {{ now()->format('d M Y h:i A') }}
    </p>

</div>

{{-- Summary --}}

<div class="section">

    <div class="section-title">

        Summary Statistics

    </div>

    <table>

        <tr>
            <th>Total Patients</th>
            <th>New Patients</th>
            <th>Total Appointments</th>
            <th>Revenue</th>
        </tr>

        <tr>
            <td>{{ $totalPatients }}</td>
            <td>{{ $newPatients }}</td>
            <td>{{ $totalAppointments }}</td>
            <td>${{ number_format($revenue,2) }}</td>
        </tr>

    </table>

</div>

{{-- Appointment Statistics --}}

<div class="section">

    <div class="section-title">

        Appointment Statistics

    </div>

    <table>

        <tr>
            <th>Pending</th>
            <th>Approved</th>
            <th>Completed</th>
            <th>Rejected</th>
        </tr>

        <tr>
            <td>{{ $pendingAppointments }}</td>
            <td>{{ $approvedAppointments }}</td>
            <td>{{ $completedAppointments }}</td>
            <td>{{ $rejectedAppointments }}</td>
        </tr>

    </table>

</div>

{{-- Medical Statistics --}}

<div class="section">

    <div class="section-title">

        Medical Statistics

    </div>

    <table>

        <tr>
            <th>Diagnoses</th>
            <th>Prescriptions</th>
        </tr>

        <tr>
            <td>{{ $diagnosesCount }}</td>
            <td>{{ $prescriptionsCount }}</td>
        </tr>

    </table>

</div>

{{-- Financial Statistics --}}

<div class="section">

    <div class="section-title">

        Financial Statistics

    </div>

    <table>

        <tr>
            <th>Total Bills</th>
            <th>Paid Bills</th>
            <th>Unpaid Bills</th>
            <th>Total Revenue</th>
        </tr>

        <tr>
            <td>{{ $totalBills }}</td>
            <td>{{ $paidBills }}</td>
            <td>{{ $unpaidBills }}</td>
            <td>${{ number_format($revenue,2) }}</td>
        </tr>

    </table>

</div>

{{-- Doctor Statistics --}}

<div class="section">

    <div class="section-title">

        Doctor Statistics

    </div>

    <table>

        <tr>
            <th>Active Doctors</th>
            <th>Top Doctor</th>
            <th>Appointments</th>
        </tr>

        <tr>

            <td>{{ $activeDoctors }}</td>

            <td>
                {{ $topDoctor?->first_name }}
                {{ $topDoctor?->last_name }}
            </td>

            <td>
                {{ $topDoctor?->appointments_count ?? 0 }}
            </td>

        </tr>

    </table>

</div>

<div style="margin-top:80px; display:flex; justify-content:space-between;">

<div>
_____________________<br>
Administrator
</div>

<div>
_____________________<br>
Clinic Manager
</div>

</div>

<div class="footer">

    <hr>
    <p>
        Generated by Quraishi Dental Clinic Management System
    </p>

    <p>
        Printed:
        {{ now()->format('d M Y h:i A') }}
    </p>

</div>


<script>
window.onload = function () {

    window.print();

    window.onafterprint = function () {
        window.close();
    };
}
</script>



</body>
</html>
